default/urls.py
from django.conf.urls import url

from . import views

app_name='default'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^tablets/$', views.tablets, name='tablets'),
    url(r'^injections/$', views.injections, name='injections'),
    url(r'^medicines/$', views.medicines, name='medicines'),
    url(r'^tab_product/(?P<product_id>[0-9]+)/$', views.tab_product, name='tab_product'),
    url(r'^inj_product/(?P<product_id>[0-9]+)/$', views.inj_product, name='inj_product'),
    url(r'^med_product/(?P<product_id>[0-9]+)/$', views.med_product, name='med_product'),
    url(r'^contact_response/$', views.contact_response, name='contact_response'),
    url(r'^sign_up/$', views.sign_up, name="sign_up"),
    url(r'^sign_in/$', views.sign_in, name="sign_in"),
    url(r'^buy_tablet/(?P<product_id>[0-9]+)/$', views.add_tablet_to_cart, name='add_tablet_to_cart'),
    url(r'^buy_injection/(?P<product_id>[0-9]+)/$', views.add_injection_to_cart, name='add_injection_to_cart'),
    url(r'^buy_medicine/(?P<product_id>[0-9]+)/$', views.add_medicine_to_cart, name='add_medicine_to_cart'),
    url(r'^remove_tablet/(?P<product_id>[0-9]+)/$', views.remove_tablet_from_cart, name='remove_tablet_from_cart'),
    url(r'^remove_injection/(?P<product_id>[0-9]+)/$', views.remove_injection_from_cart, name='remove_injection_from_cart'),
    url(r'^remove_medicine/(?P<product_id>[0-9]+)/$', views.remove_medicine_from_cart, name='remove_medicine_from_cart'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
    url(r'^alpha/(?P<alpha>[\w\-]+)/$', views.alpha, name='alpha'),

    # url(r'^contact_resp/$', views.contact_resp, name='contact_resp'),
]

genova/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from default.views import redirect_view
urlpatterns = [
    url(r'^$', redirect_view),
    url(r'^genova/', include('default.urls')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

default/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

def user_directory_path_tablets(instance, filename):
	return 'product/tablets/'+ instance.name + '.jpg'


def user_directory_path_injections(instance, filename):
	return 'product/injections/'+ instance.name + '.jpg'

def user_directory_path_medicines(instance, filename):
    return 'product/medicines/'+ instance.name + '.jpg'


class Member(models.Model):
    name = models.CharField(max_length=50)
    mobile_number = models.IntegerField()
    email = models.EmailField(blank=False)  
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)  

class Address(models.Model):
    member = models.ForeignKey(Member, blank=False, related_name="address", on_delete=models.CASCADE)
    value = models.TextField()


class Tablet(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    image =  models.ImageField(upload_to=user_directory_path_tablets)
    brand = models.CharField(max_length=200)
    description = models.TextField(null=True)
    composition = models.TextField(null=True)
    manufacturer = models.CharField(max_length=200,blank=True)
    pharmaceutical_name = models.TextField(null=True)
    unit_name = models.CharField(max_length=200,null=True)
    price_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_25 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_50 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_100 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    purchase_quantity = models.IntegerField(null=True)
    in_cart = models.ForeignKey(Member, related_name="tablet_bought", blank=True, null=True)


    def __str__(self):
    	return self.name;


class Injection(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    image =  models.ImageField(upload_to=user_directory_path_injections)
    description = models.TextField(null=True)
    brand = models.CharField(max_length=200)
    description = models.TextField(null=True)
    composition = models.TextField(null=True)
    manufacturer = models.CharField(max_length=200,blank= True)
    pharmaceutical_name = models.TextField(null=True)
    unit_name = models.CharField(max_length=200,null=True)
    price_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_25 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_50 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_100 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    purchase_quantity = models.IntegerField(null=True)
    in_cart = models.ForeignKey(Member, related_name="injection_bought", blank=True, null=True)
    def __str__(self):
    	return self.name;

class Medicine(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    image =  models.ImageField(upload_to=user_directory_path_medicines)
    description = models.TextField(null=True)
    brand = models.CharField(max_length=200)
    description = models.TextField(null=True)
    composition = models.TextField(null=True)
    manufacturer = models.CharField(max_length=200,blank= True)
    pharmaceutical_name = models.TextField(null=True)
    unit_name = models.CharField(max_length=200,null=True)
    price_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_25 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_50 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    price_100 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    purchase_quantity = models.IntegerField(null=True)
    in_cart = models.ForeignKey(Member, related_name="medicine_bought", blank=True, null=True)



    def __str__(self):
        return self.name;

default/forms.py
from django import forms
from django.core import validators
import re

class Sign_up(forms.Form):
    name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=25)
    mobile_number = forms.CharField(max_length=10)
    email = forms.CharField(max_length=60)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=20)
    repeat_password = forms.CharField(widget=forms.PasswordInput(), max_length=20)

class Login(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=20)

default/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Tablet,Injection,Medicine, Member, Address
from .forms import Login, Sign_up
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

def redirect_view(request):
    response = redirect('/genova/')
    return response

def index(request):
    return render(request, 'default/index.html')

def contact(request):
    return render(request, 'default/contact.html')

def about(request):
    return render(request, 'default/about.html')

def tablets(request):
	tablets = Tablet.objects.all()
	return render(request, 'default/tablets.html',{"tablets": tablets})

def injections(request):
	injections = Injection.objects.all()
	return render(request, 'default/injections.html',{"injections": injections})

def medicines(request):
	medicines = Medicine.objects.all()
	return render(request, 'default/medicines.html',{"medicines": medicines})

def tab_product(request,product_id):
	product = Tablet.objects.get(id=product_id)
	context = {'product':product}
	if product.price_25:
		p25 = 25 * product.price_25
		context['p25'] = p25
	if product.price_50:
		p50 = 50 * product.price_50
		context['p50'] = p50
	if product.price_100:
		p100 = 100 * product.price_100
		context['p100'] = p100
	print product_id
	return render(request, 'default/product_tab.html',context)

def inj_product(request,product_id):
	product = Injection.objects.get(id=product_id)
	context = {'product':product}
	if product.price_25:
		p25 = 25 * product.price_25
		context['p25'] = p25
	if product.price_50:
		p50 = 50 * product.price_50
		context['p50'] = p50
	if product.price_100:
		p100 = 100 * product.price_100
		context['p100'] = p100
	return render(request, 'default/product_inj.html', context)

def med_product(request,product_id):
	product = Medicine.objects.get(id=product_id)
	context = {'product':product}
	if product.price_25:
		p25 = 25 * product.price_25
		context['p25'] = p25
	if product.price_50:
		p50 = 50 * product.price_50
		context['p50'] = p50
	if product.price_100:
		p100 = 100 * product.price_100
		context['p100'] = p100
	return render(request, 'default/product_med.html', context)


def contact_response(request):
	if request.method == "POST":
		name = request.POST['NAME']
		email = request.POST['EMAIL']
		phone = request.POST['PHONE']
		subject = request.POST['SUBJECT']
		message = request.POST['MESSAGE']
		# print name, email,phone, subject, message

	return render(request, 'default/contact_form.html')

def sign_in(request):
	if request.user.is_anonymous:
		if request.method == "POST":
			form = Login(request.POST)
			if form.is_valid():
				username = form.cleaned_data.get('username')
				password = form.cleaned_data.get('password')
				current_user = authenticate(username=username, password=password)
				if current_user:
					login(request, current_user)
					current_user = request.user
					current_member = Member.objects.get(user = current_user)
					# messages.success(request, "Welcome")
					return redirect("/genova/")
				else:
					messages.error(request, "Please check your credentials")
			else:
				messages.error(request, "Please check the data you entered")
		else:
			form = Login()
			return render(request, 'default/login.html', {'form':form})
	else:
		return HttpResponse('You are already signed in')

def sign_up(request):
	if request.user.is_anonymous:
		if request.method == "POST":
			form = Sign_up(request.POST)
			if form.is_valid():
				name = form.cleaned_data.get('name')
				email = form.cleaned_data.get('email')
				username = form.cleaned_data.get('username')
				mobile_number = form.cleaned_data.get('mobile_number')
				password = form.cleaned_data.get('password')
				password2 = form.cleaned_data.get('repeat_password')
				if password == password2:
					new_user = User.objects.create_user(username=username, password=password)
					new_user.save()
					member = Member(name = name, user=new_user, email=email, mobile_number=mobile_number)
					member.save()
					return redirect("/genova/sign_in")
				else:
					return HttpResponse("The passwords do not match")
			else:
				return HttpResponse("Please check the data that you have entered")
		else:
			form=Sign_up()
			return render(request, 'default/sign_up.html', {'form':form})
	else:
		return redirect('/genova/')

def cart(request):
	if request.user.is_authenticated:
		current_user = request.user
		current_member = Member.objects.get(user = current_user)
		item_list = []
		tablet_list = current_member.tablet_bought.all()
		injection_list = current_member.injection_bought.all()
		medicine_list = current_member.medicine_bought.all()

		return render(request, 'default/cart.html', {
			'tablets':tablet_list,
			'injections':injection_list,
			'medicines':medicine_list,
			})
	else:
		return redirect('/genova/sign_in')

def sign_out(request):
	logout(request)
	messages.success(request, "You have been successfully logged out")
	return redirect('/genova/sign_in')



def add_tablet_to_cart(request, product_id):
	if request.user.is_authenticated:
		if request.method == 'POST':
			data = request.POST.get('products_id')
			current_user = request.user
			current_member = Member.objects.get(user=current_user)
			tablet = Tablet.objects.get(pk = product_id)
			current_member.tablet_bought.add(tablet)
			tablet.purchase_quantity=data
			tablet.save(update_fields=["purchase_quantity"])
			messages.success(request, "Tablet added to cart!")
			return cart(request)
		return redirect('/genova/tablets')
	else:
		return redirect('/genova/sign_in')

def remove_tablet_from_cart(request, product_id):
	current_user = request.user
	current_member = Member.objects.get(user=current_user)
	tablet = Tablet.objects.get(pk = product_id)
	current_member.tablet_bought.remove(tablet)
	messages.error(request, "Tablet removed from cart")
	return redirect('/genova/cart')


def add_injection_to_cart(request, product_id):
	if request.user.is_authenticated:
		if request.method == 'POST':
			data = request.POST.get('products_id')
			current_user = request.user
			current_member = Member.objects.get(user=current_user)
			injection = Injection.objects.get(pk = product_id)
			current_member.injection_bought.add(injection)
			injection.purchase_quantity=data
			injection.save(update_fields=["purchase_quantity"])
			messages.success(request, "Injection added to cart!")
		return redirect('/genova/injections')
	else:
		return redirect('/genova/sign_in')


def remove_injection_from_cart(request, product_id):
	current_user = request.user
	current_member = Member.objects.get(user=current_user)
	injection = Injection.objects.get(pk = product_id)
	current_member.injection_bought.remove(injection)
	messages.error(request, "Injection removed from cart")
	return redirect('/genova/cart')


def add_medicine_to_cart(request,product_id):
	if request.user.is_authenticated:
		if request.method == 'POST':
			data = request.POST.get('products_id')
			current_user = request.user
			current_member = Member.objects.get(user=current_user)
			medicine = Medicine.objects.get(pk = product_id)
			current_member.medicine_bought.add(medicine)
			medicine.purchase_quantity=data
			medicine.save(update_fields=["purchase_quantity"])
			messages.success(request, "Medicine added to cart!")
		return redirect('/genova/medicines')
	else:
		return redirect('/genova/sign_in')


def remove_medicine_from_cart(request, product_id):
	current_user = request.user
	current_member = Member.objects.get(user=current_user)
	medicine = Medicine.objects.get(pk = product_id)
	current_member.medicine_bought.remove(medicine)
	messages.error(request, "Medicine removed from cart")
	return redirect('/genova/cart')


def alpha(request,alpha):
	medicines = Medicine.objects.filter(brand=alpha)
	tablets = Tablet.objects.filter(brand=alpha)
	injections = Injection.objects.filter(brand=alpha)
	return render(request, 'default/brands.html',{"medicines": medicines,
		"tablets":tablets, "injections":injections})

default/templates/default/base.html
{% load static %}
<div class="above-everything-else">
		<div>
			<div data-collapse="medium" data-animation="default" data-duration="400" class="top-nav w-nav">
				<a href="{% url 'default:index'  %}" class="logo-top-left w-inline-block"></a>
				<nav role="navigation" class="nav-wrapper w-nav-menu">
					<div data-delay="500" class="w-dropdown">
						<div data-ix="dropdown-button" class="dropdown-toggle w-clearfix w-dropdown-toggle">
							<div class="inline-text">Products</div>
							<div class="dropdown-caret w-icon-dropdown-toggle"></div>
						</div>
						<nav data-ix="dropdown-list" class="dropdown w-dropdown-list">
							<a href="{% url 'default:tablets'  %}" id="nav_products_overview" class="dropdown-link w-dropdown-link">Tablets</a>
							<a href="{% url 'default:injections'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">Injections</a>
							<a href="{% url 'default:medicines'  %}" id="nav_products_media" class="dropdown-link w-dropdown-link">Medicines</a>
							<!-- <a href="/products/web-mobile-vr" id="nav_products_mobile" class="dropdown-link w-dropdown-link">Web &amp; Mobile VR</a>
							<a href="/products/immersive-media" id="nav_products_media" class="dropdown-link w-dropdown-link">Immersive Media</a> -->
						</nav>
					</div>
					<div data-delay="500" class="w-dropdown">
							<div data-ix="dropdown-button" class="dropdown-toggle w-clearfix w-dropdown-toggle">
								<div class="inline-text">Brands</div>
								<div class="dropdown-caret w-icon-dropdown-toggle"></div></div>
								<nav data-ix="dropdown-list" class="dropdown w-dropdown-list">
									<!-- <a href="/products" id="nav_products_overview" class="dropdown-link w-dropdown-link">Overview</a> -->
									<a href="{% url 'default:alpha' alpha='alpha'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">Alpha Pharma</a>
									<!-- <a href="/products/web-mobile-vr" id="nav_products_mobile" class="dropdown-link w-dropdown-link">Web &amp; Mobile VR</a> -->
									<a href="{% url 'default:alpha' alpha='bm'  %}" id="nav_products_media" class="dropdown-link w-dropdown-link">BM Pharma</a>
									<a href="{% url 'default:alpha' alpha='maxtreme'  %}" id="nav_products_media" class="dropdown-link w-dropdown-link">Maxtreme Pharma</a>
									<a href="{% url 'default:alpha' alpha='eminence'  %}" id="nav_products_media" class="dropdown-link w-dropdown-link">Eminence Labs</a>
								</nav>
							</div>

							<a href="{% url 'default:about'  %}"  class="nav-link w-nav-link">About</a>
	{% if user.is_authenticated %}
    	<a class="nav-link w-nav-link">{{ user.get_username }} <img src="{% static 'default/user.png' %}" width ="17px"alt=""/></a>
    	<a href="{% url 'default:sign_out'  %}"  class="nav-link w-nav-link">Logout</a>
	{% else %}
    	<a href="{% url 'default:sign_in'  %}"  class="nav-link w-nav-link">Login</a>
		<a href="{% url 'default:sign_up'  %}"  class="nav-link w-nav-link">Sign Up</a>
	{% endif %}
	<a href="{% url 'default:cart'  %}" class="nav-link w-nav-link">Cart <img src="{% static 'default/cart.png' %}" width ="20px" height ="22px" alt=""/></a>
					<!-- <a href="/faq" class="nav-link w-nav-link">FAQ</a>
					<a href="/what-is-vr-for-real-estate" class="nav-link w-nav-link">What is VR?</a> -->
					<a href="{% url 'default:contact'  %}" id="button_contact_nav" class="nav-button contact w-inline-block">
						<div>Contact</div>
					</a>
				</nav>
				<div class="menu-button-wrapper w-clearfix">
					<div class="nav-button no-line w-nav-button">
						<div class="top-nav-menu-text">Menu</div>
						<div class="menu-icon w-icon-nav-menu"></div>
					</div>
				</div>
			</div>
			<header data-ix="hide-fixed-navbar-on-load" class="fixed-topnav">
				<div data-collapse="medium" data-animation="default" data-duration="400" class="fixed-navbar w-nav">
					<a href="{% url 'default:index'  %}" class="logo-top-left w-inline-block"></a>
					<nav role="navigation" class="nav-wrapper w-nav-menu">
						<div data-delay="500" class="w-dropdown">
							<div data-ix="dropdown-button" class="dropdown-toggle w-clearfix w-dropdown-toggle">
								<div class="inline-text">Products</div>
								<div class="dropdown-caret w-icon-dropdown-toggle"></div>
							</div>
							<nav data-ix="dropdown-list" class="dropdown w-dropdown-list"><a href="{% url 'default:tablets'  %}" id="nav_products_overview" class="dropdown-link w-dropdown-link">Tablets</a>
								<a href="{% url 'default:injections'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">Injections</a>
								<a href="{% url 'default:medicines'  %}" id="nav_products_media" class="dropdown-link w-dropdown-link">Medicines</a>
								<!-- <a href="/products/web-mobile-vr" id="nav_products_mobile" class="dropdown-link w-dropdown-link">Web &amp; Mobile VR</a>
								<a href="/products/immersive-media" id="nav_products_media" class="dropdown-link w-dropdown-link">Immersive Media</a> -->
							</nav>
						</div>
						<div data-delay="500" class="w-dropdown">
											<div data-ix="dropdown-button" class="dropdown-toggle w-clearfix w-dropdown-toggle">
												<div class="inline-text">Brands</div>
												<div class="dropdown-caret w-icon-dropdown-toggle"></div></div>
												<nav data-ix="dropdown-list" class="dropdown w-dropdown-list">
													<a href="{% url 'default:alpha' alpha='alpha' %}" id="nav_products_overview" class="dropdown-link w-dropdown-link">Alpha Pharma</a>
													<a href="{% url 'default:alpha' alpha='bm'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">BM Pharma</a>
													<a href="{% url 'default:alpha' alpha='maxtreme'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">Maxtreme Pharma</a>
													<a href="{% url 'default:alpha' alpha='eminence'  %}" id="nav_products_highend" class="dropdown-link w-dropdown-link">Eminence Labs</a>
												</div><a href="{% url 'default:about'  %}" class="nav-link w-nav-link w--current">About</a>
	{% if user.is_authenticated %}
    	<a class="nav-link w-nav-link">{{ user.get_username }} <img src="{% static 'default/user.png' %}" width ="17px"alt=""/></a>
    	<a href="{% url 'default:sign_out'  %}"  class="nav-link w-nav-link">Logout</a>
	{% else %}
    	<a href="{% url 'default:sign_in'  %}"  class="nav-link w-nav-link">Login</a>
		<a href="{% url 'default:sign_up'  %}"  class="nav-link w-nav-link">Sign Up</a>
	{% endif %}
	<a href="{% url 'default:cart'  %}" class="nav-link w-nav-link">Cart <img src="{% static 'default/cart.png' %}" width ="20px" height ="22px" alt=""/></a>
						<a href="{% url 'default:contact'  %}" id="button_contact_nav" class="nav-button contact w-inline-block">
							<div>Contact</div>
						</a>
					</nav>
					<div class="menu-button-wrapper w-clearfix">
						<div class="nav-button no-line w-nav-button">
							<div class="top-nav-menu-text">Menu</div>
							<div class="menu-icon w-icon-nav-menu"></div>
						</div>
					</div>
				</div>
			</header>

default/templates/default/template1.html
{% if messages %}
<ul>
	{% for message in messages %}
	   <li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}